### ISSUE TITLE
Newton solver did not converge warning 

### ISSUE THREAD

**Issue by Stray357** [Layton-Lab/nephron#6]
Hi,
  I'm trying to run the script on baseline setting by the command "python parallel_simulate.py --sex Male --species rat --type multiple". The simulation seemed to be fine at the start but started to pop up warnings like below
![image](https://user-images.githubusercontent.com/62871453/202063854-d85a4409-f6cf-4849-a0e2-3a2de178a21a.png)
I do not have a math background so I really cannot tell whether this is fine, or should I be alerted by that.
I'm running the script on python 3.8.8, if that might help.

Thanks a lot!

**Comment by Stray357** [comment]
After the program stopped I got the trace back information as bellow
![nephron trace back-blocked](https://user-images.githubusercontent.com/62871453/202092334-1e589a9b-37e9-415e-a56f-e4944c8ef3c3.jpg)
and an output file folder named Male_rat_normal. The files inside the folder were named exactly like the README file has described, but I cannot figure out what does each number mean in the whole column of numbers.
![image](https://user-images.githubusercontent.com/62871453/202094918-b4786dd0-2d21-4a42-a260-78ab8db1701b.png)
Above is the result opened from file 'male_rat_DCT_NaKATPase_Na14_sup.txt' . For example, would you please explain what does the "811.136383329922" in the first row and the "876.0873773433023" in the second row indicated?

I know I'm very new in this field, but your work really seems exciting and I'd like to learn more about it.
Thanks  a lot !

**Comment by mstadt** [comment]
Newton's method is the method we use to solve the nonlinear system of equations. When it doesn't converge, there is an error size. To help converge best is to change the "amp" parameter in the newton solver used (Newton.py script). This will put you in a different solution space to then reach convergence. 

The error size is how off the solution is from getting a 0
